"""mudando o nome do novo campo

Revision ID: 09444f42c4b6
Revises: a4a8f704301e
Create Date: 2025-06-23 22:42:43.322183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09444f42c4b6'
down_revision: Union[str, None] = 'a4a8f704301e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_cover', sa.String(), nullable=True))
    op.drop_column('books', 'cover_book')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_book', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('books', 'book_cover')
    # ### end Alembic commands ###
