"""att com o campo da tabela [book]

Revision ID: 4e23b807f740
Revises: 7216ae07d82c
Create Date: 2025-04-26 16:59:55.571343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e23b807f740'
down_revision: Union[str, None] = '7216ae07d82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('file_book', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'books', ['file_book'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'file_book')
    # ### end Alembic commands ###
