"""adicionando tabelas novelist e books

Revision ID: f2b2ff9347e6
Revises: 434d09a7f751
Create Date: 2024-09-29 07:05:15.874281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b2ff9347e6'
down_revision: Union[str, None] = '434d09a7f751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
